//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int property_number { get; set; }
        public string formatted_address { get; set; }
        public Nullable<int> house_number { get; set; }
        public string house_number_suffix { get; set; }
        public Nullable<int> house_number_to { get; set; }
        public string house_number_to_suffix { get; set; }
        public string locality { get; set; }
        public string postcode { get; set; }
        public string property_name { get; set; }
        public string street { get; set; }
        public Nullable<int> unit_number { get; set; }
        public string unit_number_suffix { get; set; }
        public Nullable<int> unit_number_to { get; set; }
        public string unit_number_to_suffix { get; set; }
    }
}
